using System.Text.Json;
using ControlManagement.Security;

namespace ControlManagement.Api.Validation;

public sealed class RepositoryCommandValidator
{
    private static readonly HashSet<string> Statuses = new(StringComparer.OrdinalIgnoreCase)
        { "Active", "Inactive", "Draft", "Review", "Approved", "Published", "Retired", "Open", "Closed", "Pending", "Sent", "Read" };

    // Assurance Management (Phase 1) lifecycle actions; validated separately from
    // the shared SAVE / RETIRE / APPROVE / REJECT actions.  All require a valid
    // record id and only accept an optional 'remarks' payload.
    private static readonly HashSet<string> AssuranceLifecycleActions = new(StringComparer.OrdinalIgnoreCase)
        { "SUBMIT", "PUBLISH", "RETIRE_PUBLISHED" };

    private static readonly Dictionary<string, string[]> Required = new(StringComparer.OrdinalIgnoreCase)
    {
        ["authorities"] = ["code", "name"],
        ["artifacts"] = ["authorityId", "code", "name", "category"],
        ["releases"] = ["artifactId", "version"],
        ["statement-classifications"] = ["releaseId", "name"],
        ["source-structure"] = ["releaseId", "nodeType", "reference", "title"],
        ["framework-statements"] = ["releaseId", "structureNodeId", "statementReference", "statementText"],
        ["controls"] = ["code", "name"],
        ["control-domains"] = ["name"],
        ["control-sub-domains"] = ["domainId", "name"],
        // Practice Code is system-generated by cm_manage_repository (PR-001,
        // PR-002, ...) when the payload does not carry one, so it is not a
        // required field here -- see database/050_practice_code_autogen.sql.
        ["requirements"] = ["name", "statement"],
        ["obligations"] = ["obligationName"],
        // Composite save (Phase 2): master name + the type discriminator are
        // the only fields required at the envelope level.  Type-specific
        // required fields are enforced by cm_manage_obligation_composite so
        // the rule lives next to the taxonomy it belongs to.
        ["obligation-composite"] = ["obligationName", "obligationTypeCode"],
        // Event-driven assurance runtime (035/036) accepts several payload
        // shapes on the same entity type, keyed by the tunnelled _action:
        //   RAISE  => { eventTypeId, subjectEntity, subjectRecordId, ... }
        //   CANCEL => { remarks }
        // A single required-field list would reject CANCEL, so this entry is
        // intentionally empty and the dedicated branch in Validate() applies
        // the RAISE contract only when the action is actually RAISE.
        // cm_manage_assurance_runtime re-validates everything regardless.
        ["assurance-occurrences"] = [],
        ["obligation-mappings"] = ["obligationId", "requirementId", "releaseId"],
        ["obligation-mapping-bulk"] = ["requirementId"],
        ["control-requirement-mappings"] = ["controlId"],
        // 'source-control-mappings' accepts two payload shapes:
        //   (a) Practice -> Framework Statement mapping (main screen)
        //       => { frameworkStatementId, requirementIds[], status }
        //   (b) Legacy Control -> Structure Node mapping (Add/Edit Control form)
        //       => { structureNodeId, controlIds[], status }
        // Because the required field differs between the two, this entry is
        // intentionally not populated with a single required key here — the
        // dedicated branch inside Validate() below enforces "at least one of
        // requirementIds or controlIds must be present".  The stored procedure
        // still enforces the full contract (framework statement / structure
        // node / target list) as the final safety net.
        ["source-control-mappings"] = [],
        ["applicability-rules"] = ["name", "expression", "priority", "outcome"],
        ["user-management"] = ["userName", "loginId", "email"],
        ["role-management"] = ["roleName"],
        ["menu-management"] = ["menuName", "menuCode", "displayOrder"],
        ["role-permissions"] = ["roleId", "menuId"],
        ["changes"] = ["entityType", "entityId", "changeType", "summary", "severity", "status"],
        ["impact-analysis"] = ["changeEventId", "impactedEntityType", "impactedEntityId", "status"],
        ["notifications"] = ["type", "subject", "message", "severity", "status"],
        ["approval-workflow"] = ["moduleName", "approvalRequired", "selfApprovalAllowed", "minimumApprovers"],
        // Assurance Management (Phase 1 - Admin / Authority Control Module).
        // Every metadata master requires Code + Name; downstream fields are
        // enforced by the stored procedure so lifecycle transitions can share
        // the same required-field contract.
        ["assurance-categories"] = ["code", "name"],
        ["assurance-scoring-models"] = ["code", "name"],
        ["assurance-severity"] = ["code", "name"],
        ["assurance-gap-categories"] = ["code", "name"],
        ["assurance-workflow-templates"] = ["code", "name"],
        ["assurance-question-types"] = ["code", "name"],
        ["assurance-sampling-models"] = ["code", "name"],
        ["assurance-frequency-types"] = ["code", "name"],
        ["assurance-report-templates"] = ["code", "name"],
        ["assurance-starter-templates"] = ["code", "name"]
    };

    public string? Validate(SecureRepositoryRequest request)
    {
        if (request.EntityType.Equals("audit-trace", StringComparison.OrdinalIgnoreCase)
            || request.EntityType.Equals("lookups", StringComparison.OrdinalIgnoreCase)
            || request.EntityType.Equals("assurance-version-history", StringComparison.OrdinalIgnoreCase)
            || request.EntityType.Equals("assurance-lookups", StringComparison.OrdinalIgnoreCase))
            return "This repository area is read-only.";

        // Assurance lifecycle transitions (SUBMIT/PUBLISH/RETIRE_PUBLISHED) act on
        // an existing record id.  Any remarks payload is optional and capped.
        if (AssuranceLifecycleActions.Contains(request.Action))
        {
            if (request.Id.GetValueOrDefault() <= 0) return "A valid record identifier is required.";
            if (request.Data.ValueKind == JsonValueKind.Object
                && request.Data.TryGetProperty("remarks", out var lifecycleRemarks)
                && lifecycleRemarks.GetString()?.Length > 1000)
                return "Remarks cannot exceed 1000 characters.";
            return null;
        }
        if (request.Action.Equals("APPROVE", StringComparison.OrdinalIgnoreCase))
        {
            if (request.Id.GetValueOrDefault() <= 0) return "A valid record identifier is required.";
            if (request.Data.TryGetProperty("comments", out var comments) && comments.GetString()?.Length > 1000)
                return "Approval comments cannot exceed 1000 characters.";
            return null;
        }
        if (request.Action.Equals("REJECT", StringComparison.OrdinalIgnoreCase)
            || request.Action.Equals("SEND_BACK", StringComparison.OrdinalIgnoreCase))
        {
            if (request.Id.GetValueOrDefault() <= 0) return "A valid record identifier is required.";
            if (!request.Data.TryGetProperty("comments", out var comments) || string.IsNullOrWhiteSpace(comments.GetString()))
                return "Checker comments are mandatory.";
            if (comments.GetString()?.Length > 1000) return "Checker comments cannot exceed 1000 characters.";
            return null;
        }
        // RETIRE, its mirror ACTIVATE, and the read-only RETIRE_IMPACT preview
        // all act on an existing record id and carry no payload of their own.
        if (request.Action.Equals("RETIRE", StringComparison.OrdinalIgnoreCase)
            || request.Action.Equals("ACTIVATE", StringComparison.OrdinalIgnoreCase)
            || request.Action.Equals("RETIRE_IMPACT", StringComparison.OrdinalIgnoreCase))
            return request.Id.GetValueOrDefault() > 0 ? null : "A valid record identifier is required.";
        if (!request.Action.Equals("SAVE", StringComparison.OrdinalIgnoreCase)) return "Unsupported repository action.";
        if (request.Data.ValueKind != JsonValueKind.Object) return "A valid request payload is required.";
        if (request.Data.GetRawText().Length > 100_000) return "The request payload is too large.";

        // 'obligations' is now a standalone master form.  No Requirement / Release
        // is required at save-time; the maker maps Obligation -> Requirement +
        // Release later through the 'obligation-mappings' entity.

        foreach (var name in Required.GetValueOrDefault(request.EntityType, []))
            if (!request.Data.TryGetProperty(name, out var value) || IsEmpty(value))
                return $"{name} is required.";

        // 'assurance-occurrences' - the RAISE contract applies only when the
        // tunnelled action is RAISE.  CANCEL sends only remarks, and the
        // browser gateway squashes every POST to Action = SAVE, so the real
        // intent is read from the payload the same way the SP reads it.
        if (request.EntityType.Equals("assurance-occurrences", StringComparison.OrdinalIgnoreCase))
        {
            var tunnelled = request.Data.TryGetProperty("_action", out var actionEl)
                ? actionEl.GetString() ?? ""
                : "";
            var isRaise = tunnelled.Length == 0
                          || tunnelled.Equals("RAISE", StringComparison.OrdinalIgnoreCase)
                          || tunnelled.Equals("SAVE", StringComparison.OrdinalIgnoreCase);
            if (isRaise)
            {
                foreach (var name in new[] { "eventTypeId", "subjectEntity", "subjectRecordId" })
                    if (!request.Data.TryGetProperty(name, out var value) || IsEmpty(value))
                        return $"{name} is required.";
            }
            else if (tunnelled.Equals("CANCEL", StringComparison.OrdinalIgnoreCase))
            {
                if (request.Id.GetValueOrDefault() <= 0) return "A valid checklist identifier is required.";
                if (!request.Data.TryGetProperty("remarks", out var reason) || IsEmpty(reason))
                    return "A reason is required to cancel a checklist.";
            }
        }

        // 'source-control-mappings' - enforce the "at least one target list" rule
        // for the two supported payload shapes (Practice mapping vs legacy
        // Control mapping).  See comment on the Required entry above.
        if (request.EntityType.Equals("source-control-mappings", StringComparison.OrdinalIgnoreCase))
        {
            var hasRequirements = request.Data.TryGetProperty("requirementIds", out var reqIds) && !IsEmpty(reqIds);
            var hasControls = request.Data.TryGetProperty("controlIds", out var ctlIds) && !IsEmpty(ctlIds);
            if (!hasRequirements && !hasControls)
                return "Select at least one Practice (or Control) to map.";
            var hasFrameworkStatement = request.Data.TryGetProperty("frameworkStatementId", out var fsId) && !IsEmpty(fsId);
            var hasStructureNode = request.Data.TryGetProperty("structureNodeId", out var snId) && !IsEmpty(snId);
            if (!hasFrameworkStatement && !hasStructureNode)
                return "A Framework Statement (or Source Structure node) is required for the mapping.";
        }

        if (request.EntityType.Equals("authorities", StringComparison.OrdinalIgnoreCase)
            && request.Data.TryGetProperty("code", out var authorityCode)
            && authorityCode.GetString()?.Trim().Length > 80)
            return "Authority Code cannot exceed 80 characters.";
        if (request.EntityType.Equals("artifacts", StringComparison.OrdinalIgnoreCase)
            && request.Data.TryGetProperty("code", out var artifactCode)
            && artifactCode.GetString()?.Trim().Length > 100)
            return "Artifact Code cannot exceed 100 characters.";

        if (request.Data.TryGetProperty("status", out var status)
            && status.ValueKind == JsonValueKind.String
            && !Statuses.Contains(status.GetString() ?? ""))
            return "The selected status is invalid.";
        return null;
    }

    private static bool IsEmpty(JsonElement value) =>
        value.ValueKind is JsonValueKind.Null or JsonValueKind.Undefined
        || value.ValueKind == JsonValueKind.String && string.IsNullOrWhiteSpace(value.GetString())
        || value.ValueKind == JsonValueKind.Array && value.GetArrayLength() == 0
        || value.ValueKind == JsonValueKind.Number && value.TryGetInt64(out var number) && number <= 0;
}
